//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentAp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public string senderId { get; set; }
        public string receiverId { get; set; }
        public Nullable<float> amount { get; set; }
    
        public virtual client client { get; set; }
        public virtual client client1 { get; set; }
    }
}
