
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eproject3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contest
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contest()
    {

        this.Exams = new HashSet<Exams>();

        this.Contester = new HashSet<Contester>();

    }


    public int id { get; set; }

    public Nullable<System.DateTime> C_Time { get; set; }

    public Nullable<System.DateTime> exp_time { get; set; }

    public string C_Description { get; set; }

    public string img { get; set; }

    public Nullable<int> id_winner { get; set; }

    public string title { get; set; }

    public string requirement { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Exams> Exams { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contester> Contester { get; set; }

    public virtual Contester Contester1 { get; set; }

}

}
