

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Eproject3.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DatabaseEntities : DbContext
{
    public DatabaseEntities()
        : base("name=DatabaseEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Contest> Contest { get; set; }

    public virtual DbSet<Contester> Contester { get; set; }

    public virtual DbSet<Exams> Exams { get; set; }

    public virtual DbSet<FeedBack> FeedBack { get; set; }

    public virtual DbSet<Packs> Packs { get; set; }

    public virtual DbSet<Recipes> Recipes { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Tips> Tips { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

}

}

